services:
  - type: web
    name: stock-market-dash
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dash_app:server
    autoDeploy: true
